import org.code.neighborhood.*;

import org.code.neighborhood.*;
// creates a wave class and makes it extend the background painter
public class Ocean extends RightWave {
  public void drawOcean() {
    drawBottom();
  }

  public void drawBottom() {
    //Draws the ocean under the wave on the grid
  move();
    turnRight();
  move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    turnLeft();
     paintLine("white", 3);
     paintLine("skyblue", 1);
     paintLine("blue", 3);
     paintLine("skyblue", 1);
     paintLine("white", 4);
     paintLine("skyblue", 1);
    turnRight();
    move();
    turnRight();
     paintLine("skyblue", 1);
     paintLine("white", 4);
     paintLine("skyblue", 1);
     paintLine("blue", 1);
     paintLine("skyblue", 1);
     paintLine("white", 2);
    turnLeft();
    move();
    turnLeft();
    paintLine("white", 3);
     paintLine("blue", 3);
     paintLine("skyblue", 1);
     paintLine("white", 4);
     paintLine("skyblue", 1);
    turnRight();
    move();
    turnRight();
    move();
    paintLine("white", 2);
     paintLine("blue", 1);
     paintLine("skyblue", 1);
     paintLine("blue", 2); 
     paintLine("white", 1);
     paintLine("blue", 2);
     paintLine("skyblue", 1);
     paintLine("blue", 2);
     paintLine("skyblue", 1);
      paintLine("white", 2);
    turnLeft();
    move();
    turnLeft();
      paintLine("white", 17);
      paintLine("skyblue", 1);
    move();
    move();
    move();
    move();
    move();
    move();
      paintLine("white", 2);
      paintLine("skyblue", 1);
      paintLine("blue", 1);
      paintLine("skyblue", 2);
      paintLine("blue", 1);
    turnRight();
      paintLine("blue", 1);
    turnRight();
      paintLine("skyblue", 1);
      paintLine("white", 1);
      paintLine("skyblue", 2);
      paintLine("blue", 3);
      paintLine("skyblue", 1);
      paintLine("blue", 1);
      paintLine("white", 4);
    move();
    move();
      paintLine("white", 5);
      paintLine("blue", 2);
      paintLine("white", 9);
    turnLeft();
      paintLine("white", 1);
    turnLeft();
      paintLine("white", 9);
      paintLine("skyblue", 1);
      paintLine("white", 1);
      paintLine("blue", 1);
      paintLine("skyblue", 1);
      paintLine("white", 6);
      paintLine("blue", 2);
      paintLine("skyblue", 1);
      paintLine("blue", 2);
        paintLine("skyblue", 2); 
      paintLine("blue", 1);
      paintLine("white", 2);
      paintLine("blue", 2);
    
    turnRight();
      paintLine("white", 1);
    turnRight();
      paintLine("blue", 1);
      paintLine("white", 1);
      paintLine("blue", 2);
      paintLine("white", 4);
      paintLine("skyblue", 1);
      paintLine("blue", 2);
      paintLine("white", 2);
      paintLine("blue", 2);
      paintLine("white", 1);
      paintLine("skyblue", 1);
      paintLine("blue", 2);
      paintLine("white", 1);
      paintLine("skyblue", 1);
      paintLine("blue", 2);
      paintLine("white", 1);
      paintLine("skyblue", 1);
      paintLine("blue", 1);
      paintLine("white", 5);
    turnLeft();
      paintLine("white", 1);
    turnLeft();
      paintLine("white", 3);
      paintLine("skyblue", 2);
      paintLine("white", 1);
      paintLine("blue", 1);
      paintLine("skyblue", 1);
        paintLine("blue", 2);
         paintLine("skyblue", 1);
         paintLine("white", 1);
      paintLine("blue", 2);
      paintLine("skyblue", 1);
      paintLine("blue", 3);
      paintLine("skyblue", 2);
      paintLine("white", 5);
      paintLine("skyblue", 3);
      paintLine("blue", 1);
      paintLine("white", 1);
      paintLine("blue", 1);
    turnRight();
      paintLine("white", 1);
    turnRight();
    paintLine("skyblue", 1);
      paintLine("white", 1);
      paintLine("skyblue", 2);
      paintLine("blue", 3);
      paintLine("skyblue", 1);
      paintLine("blue", 1);
      paintLine("white", 4);
      paintLine("skyblue", 1);
      paintLine("blue", 3);
      paintLine("skyblue", 2);
      paintLine("white", 5);
      paintLine("skyblue", 3);
      paintLine("blue", 1);
    paintLine("skyblue", 1);
    paintLine("blue", 2);
    turnLeft();
    paintLine("blue", 1);
    turnLeft();
         paintLine("white", 2);
      paintLine("skyblue", 1);
      paintLine("blue", 1);
      paintLine("skyblue", 2);
      paintLine("blue", 1);
     paintLine("white", 2);
    paintLine("white", 9);
      paintLine("skyblue", 1);
      paintLine("white", 1);
      paintLine("blue", 1);
      paintLine("skyblue", 1);
      paintLine("white", 6);
      paintLine("blue", 2);
      paintLine("skyblue", 1);
    turnRight();
      paintLine("blue", 1);
    turnRight();
     paintLine("skyblue", 1);
     paintLine("blue", 2);
     paintLine("white", 1);
     paintLine("blue", 2);
     paintLine("skyblue", 1);
     paintLine("blue", 2);
     paintLine("skyblue", 1);
     paintLine("blue", 1);
     paintLine("white", 2);
     paintLine("skyblue", 1);
     paintLine("white", 4);
     paintLine("skyblue", 1);
     paintLine("blue", 1);
     paintLine("skyblue", 1);
     paintLine("white", 2);
    paintLine("blue", 2);
      paintLine("skyblue", 1);
      paintLine("blue", 3);
      paintLine("skyblue", 2);
    turnLeft();
    paintLine("white", 1);
    turnLeft();
    paintLine("white", 7);
     paintLine("skyblue", 1);
     paintLine("blue", 3);
     paintLine("skyblue", 1);
      paintLine("blue", 2);
      paintLine("white", 2);
      paintLine("blue", 2);
      paintLine("white", 1);
      paintLine("skyblue", 1);
      paintLine("blue", 2);
      paintLine("white", 1);
      paintLine("skyblue", 1);
      paintLine("blue", 2);
      paintLine("white", 1);
      paintLine("skyblue", 1);
      paintLine("blue", 1);
      paintLine("white", 2);
    turnRight();
    paintLine("skyblue", 1);
    turnRight();
    paintLine("white", 2);
     paintLine("blue", 1);
     paintLine("skyblue", 1);
     paintLine("blue", 2); 
     paintLine("white", 1);
     paintLine("blue", 2);
     paintLine("skyblue", 1);
     paintLine("blue", 2);
     paintLine("skyblue", 1);
      paintLine("white", 2);
     paintLine("skyblue", 1);
     paintLine("blue", 3);
     paintLine("skyblue", 1);
    paintLine("skyblue", 1);
      paintLine("white", 1);
      paintLine("skyblue", 2);
      paintLine("blue", 3);
      paintLine("skyblue", 1);
      paintLine("blue", 3);
    turnRight();
    paintLine("skyblue", 1);
    turnRight();
    turnRight();
    move();
    turnLeft();
    moveFast();


   
   
    
    
     
}
  
  
  
}