import org.code.neighborhood.*;

import org.code.neighborhood.*;
// creates a wave class and makes it extend the background painter
public class Wave extends BackgroundPainter {
  public void drawWave() {
    drawBigWave();
  }

  public void drawBigWave() {
    //Sends a painter to paint the top left and bottom of the wave
    moveFast();
    turnRight();
    move();
    turnRight();
    moveFast();
    turnLeft();
    move();
    turnLeft();
    moveFast();
    turnRight();
    move();
    turnRight();
    moveFast();
    turnLeft();
    move();
    turnLeft();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
   paintLine("white", 6);
    move();
    turnRight();
    move();
    turnRight();
    paintLine("white", 9);
    move();
    turnLeft();
    move();
    turnLeft();
    paintLine("white", 6);
    paintLine("blue", 1);
     paintLine("white", 6);
    move();
     paintLine("white", 1);
    turnRight();
    move();
    turnRight();
     paintLine("white", 1);
    move();
     paintLine("white", 1);
    move();
     paintLine("white", 4);
     paintLine("blue", 1);
     paintLine("white", 6);
    move();
    turnLeft();
    move();
    turnLeft();
     paintLine("white", 5);
     paintLine("skyblue", 1);
 paintLine("blue", 2);
     paintLine("skyblue", 2);
     paintLine("white", 4);
    move();
    move();
    turnRight();
    move();
    turnRight();
    move();
     paintLine("white", 2);
    move();
     paintLine("white", 2);
     paintLine("blue", 3);
     paintLine("skyblue", 1);
     paintLine("blue", 2);
     paintLine("white", 5);
    turnLeft();
    move();
    turnLeft();
     paintLine("white", 7);
     paintLine("skyblue", 1);
     paintLine("blue", 3);
     paintLine("skyblue", 1);
    move();
    move();
    paintLine("white", 1);
    move();
     paintLine("white", 2);
    turnRight();
    move();
    turnRight();
    move();
     paintLine("white", 1);
    move();
    move();
    move();
    move();
    move();
    move();
     paintLine("skyblue", 1);
     paintLine("blue", 2);
     paintLine("white", 2);
     paintLine("blue", 1);
     paintLine("white", 6);
    turnLeft();
    move();
    turnLeft();
    move();
     paintLine("white", 2);
      paintLine("blue", 1);
      paintLine("skyblue", 1);
      paintLine("white", 2);
      paintLine("blue", 2);
      paintLine("skyblue", 1);
      paintLine("blue", 1);
      paintLine("skyblue", 1);
     turnRight();
    move();
    turnRight();
    move();
      paintLine("skyblue", 1);
      paintLine("skyblue", 1);
      paintLine("white", 2);
      paintLine("blue", 2);
      paintLine("skyblue", 1);
      paintLine("white", 5);
    turnLeft();
    move();
    turnLeft();
    move();
      paintLine("white", 4);
      paintLine("blue", 1);
      paintLine("skyblue", 1);
      paintLine("white", 1);
      paintLine("blue", 1);
      paintLine("white", 1);
      paintLine("blue", 1);
      paintLine("skyblue", 1);
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    paintLine("white", 1);
    turnRight();
    move();
    turnRight();
   move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
     paintLine("skyblue", 1);
     paintLine("blue", 1);
      paintLine("skyblue", 1);
     paintLine("blue", 2);
     paintLine("skyblue", 1);
     paintLine("blue", 1);
     paintLine("white", 1);
     paintLine("skyblue", 1);
     paintLine("blue", 1);
     paintLine("white", 3);
    turnLeft();
    move();
    turnLeft();
     paintLine("white", 2);
     paintLine("blue", 1);
     paintLine("skyblue", 1);
     paintLine("blue", 2); 
     paintLine("white", 1);
     paintLine("blue", 2);
     paintLine("skyblue", 1);
     paintLine("blue", 2);
     paintLine("skyblue", 1);
    turnRight();
    move();
    turnRight();
    move();
     paintLine("skyblue", 1);
     paintLine("blue", 2);
     paintLine("white", 1);
     paintLine("blue", 2);
     paintLine("skyblue", 1);
     paintLine("blue", 2);
     paintLine("skyblue", 1);
     paintLine("blue", 1);
     paintLine("white", 2);
    turnLeft();
    move();
    turnLeft();
    move();
    turnRight();
    move();
  
    

    
    
     
}
  
  
  
}